# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    bootstrap.twig.bootstrap_extension:
        class: Anezi\Bundle\BootstrapBundle\Twig\BootstrapExtension
        tags:
            - { name: twig.extension }

    timer.provider.matsport:
        class: AppBundle\Timer\Provider\Matsport

    timer.timer:
        class: AppBundle\Timer\Timer
        calls:
            - [ setEm, [ "@doctrine.orm.entity_manager" ] ]
